# A generic, single database configuration for Alembic.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s

# sys.path path list to be prepended to sys.path and in use when template-rendering
# prepend_sys_path = .

# timezone to use when rendering the date
# timezone =

# max length of characters to write to changelog
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded from local path
# version_locations = %(here)s/migrations/versions

# version path separator; defaults to os.pathsep.
# Use a space to allow newline-separated listing in Windows/POSIX
# version_path_separator = ' '

sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/probot

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
